# Build Stage 1
FROM node:24-alpine AS build
WORKDIR /app

# Copy package.json, package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Copy the entire project
COPY . ./

# Build the project
RUN npm run build

# Build Stage 2
FROM node:24-alpine
WORKDIR /app

# Copy the build output
COPY --from=build /app/.output/ ./

EXPOSE 3000

CMD ["node", "/app/server/index.mjs"]
